server:
  port: 8086

spring:
  datasource:
   password: Nikhil@07@18
   url: jdbc:postgresql://localhost:5432/hotelmicroservice
   username: root   
   
  application:
    name: HOTEL-SERVICE
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect  
  config:
    import: optional:configserver:http://localhost:9090   