server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicro
    username: root
    password: Nikhil@07@18
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  application:
     name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect  
      
     
  config:
    import: optional:configserver:http://localhost:9090 
       
#eureka:
#  instance:
#   prefer-ip-address: true
#  client:
#    fetch-registry: true 
#    register-with-eureka: true
#    service-url:
#       defaultZone: http://localhost:8761/eureka
      