server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicro
    username: root
    password: Nikhil@07@18
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true