server:
  port: 8088
  
spring:
  datasource:
    password: Nikhil@07@18
    url: jdbc:postgresql://localhost:5432/ratingsservice
    username: root
 
  application:
    name: RATING-SERVICE
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  config:
    import: optional:configserver:http://localhost:9090         